on:
  workflow_dispatch:
  push:
  #   tags:
  #     - 'v*.*.*'
  #     - '*.*.*'
  # pull_request:

env:
  VERSION: 3.5.4
  DOCKER_PLATFORMS: linux/amd64,linux/arm64
  PUSH_REGISTRY: ghcr.io/${{github.repository}}
  GCR_REGISTRY: "europe-west3-docker.pkg.dev/rasa-releases/rasa-plus"

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate with Gcloud
      - name: Authenticate with gcloud for release registry 🎫
        id: 'auth-release'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d'
        with:
          credentials_json: '${{ secrets.GCR_JSON_KEY }}'
          # service_account: '${{ secrets.GCR_JSON_KEY }}'

      # Authenticate with artifact registry where the images are stored.
      - name: Authenticate docker for release registry 🎫
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - id: registry
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{env.GCR_REGISTRY}}

      - name: Build and tag image ready for pushing to dev and release registries
        run: |
          docker build . -t ${{ steps.registry.outputs.lowercase }}/rasa-plus:${{ env.VERSION }} -t ${{env.PUSH_REGISTRY}}:${{ env.VERSION }} -t ${{env.PUSH_REGISTRY}}:latest --build-arg VERSION=${{ env.VERSION }} -f Dockerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image to release registry
        run: |
          docker push ${{ steps.registry.outputs.lowercase }}:${{ env.VERSION }}
          docker push ${{ steps.registry.outputs.lowercase }}:latest
