on:
  workflow_dispatch:
  push:
  #   tags:
  #     - 'v*.*.*'
  #     - '*.*.*'
  # pull_request:

env:
  VERSION: 3.5.4
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # https://github.com/crazy-max/ghaction-docker-meta
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          #  ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          images: |
            ghcr.io/${{ github.repository }}
          tag-semver: |
            {{version}}

      - name: Show envs if image-tag
        if: ${{ github.event.inputs.image-tag }}
        run: |
          echo "github.event.inputs.image-tag: ${{ github.event.inputs.image-tag }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build & Push
        id: build_gcr
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{ env.VERSION }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
#          image: ${{ github.repository }}
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
